# Generated by Django 5.2 on 2026-03-25 04:27

import portfolio.models
import portfolio.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_upload',
            field=models.FileField(blank=True, help_text='Upload file here to save automatically into static/images/projects/', null=True, storage=portfolio.storages.ProjectStaticStorage(), upload_to=portfolio.models.project_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.CharField(blank=True, default='', help_text='Fallback static path, e.g. /static/images/img.png', max_length=255),
        ),
    ]
