# Generated by Django 5.2 on 2026-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_cover_upload_alter_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, default='', help_text='Public link for visiting this project.'),
        ),
    ]
